import { GitPullRequest, AlertCircle, Shoe } from "tabler-icons-react";
import { GiBroom } from "react-icons/gi";
export const dummyTasks = [
  {
    icon: <GitPullRequest size={16} />,
    color: "purple",
    label: "Cleaning shoes",
    category: "Cleaning",
    jobTime: "Thur 12 March",
    location: "Amsterdam",
    offer: 15,
    status: "open",
    comments: 3,
    applicants: 5,
    jid: "23456gfadsgfa78",
    owner: {
      name: "Elko Lemiso",
      profileImage: "",
      uuid: "123456789",
    },
    timePosted: "6 hours",
    taskDescription:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sit amet suscipit nisl. Maecenas lorem neque, feugiat quis est tincidunt, ultrices aliquet risus. Aliquam vitae mollis lacus, quis iaculis felis. Ut ac mauris varius, scelerisque justo ac, sodales ligula. Fusce vestibulum massa in dictum bibendum. Sed imperdiet commodo dui, quis bibendum ipsum mattis ac. Vivamus a congue velit. Pellentesque sed pulvinar dolor.",
    taskersNeeded: 2,
    requirements: ["2 taskers", "Muscles", "A toothbrush", "Philosophy degree"],
  },
  {
    icon: <AlertCircle size={16} />,
    color: "teal",
    label: "Cleaning shoes",
    category: "Cleaning",
    jobTime: "Thur 12 March",
    location: "Amsterdam",
    offer: 15,
    status: "open",
    comments: 3,
    applicants: 5,
    jid: "23456gfadsgiifa78",
    owner: {
      name: "Elko Lemiso",
      profileImage: "",
      uuid: "123456789",
    },
    timePosted: "6 hours",
    taskDescription:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sit amet suscipit nisl. Maecenas lorem neque, feugiat quis est tincidunt, ultrices aliquet risus. Aliquam vitae mollis lacus, quis iaculis felis. Ut ac mauris varius, scelerisque justo ac, sodales ligula. Fusce vestibulum massa in dictum bibendum. Sed imperdiet commodo dui, quis bibendum ipsum mattis ac. Vivamus a congue velit. Pellentesque sed pulvinar dolor.",
    taskersNeeded: 2,
    requirements: ["2 taskers", "Muscles", "A toothbrush", "Philosophy degree"],
  },
  {
    icon: <Shoe size={16} />,
    color: "violet",
    label: "Cleaning shoes",
    category: "Cleaning",
    jobTime: "Thur 12 March",
    location: "Amsterdam",
    offer: 15,
    status: "open",
    comments: 3,
    applicants: 5,
    jid: "23456gfasxgjfxdsgfa78",
    owner: {
      name: "Elko Lemiso",
      profileImage: "",
      uuid: "123456789",
    },
    timePosted: "6 hours",
    taskDescription:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sit amet suscipit nisl. Maecenas lorem neque, feugiat quis est tincidunt, ultrices aliquet risus. Aliquam vitae mollis lacus, quis iaculis felis. Ut ac mauris varius, scelerisque justo ac, sodales ligula. Fusce vestibulum massa in dictum bibendum. Sed imperdiet commodo dui, quis bibendum ipsum mattis ac. Vivamus a congue velit. Pellentesque sed pulvinar dolor.",
    taskersNeeded: 2,
    requirements: ["2 taskers", "Muscles", "A toothbrush", "Philosophy degree"],
  },
  {
    icon: <GiBroom size={16} />,
    color: "grape",
    label: "Cleaning shoes ",
    category: "Cleaning",
    jobTime: "Thur 12 March",
    location: "Amsterdam",
    offer: 15,
    status: "open",
    comments: 3,
    applicants: 5,
    jid: "23456gfgsdgasrgradsgfa78",
    owner: {
      name: "Elko Lemiso",
      profileImage: "",
      uuid: "123456789",
    },
    timePosted: "6 hours",
    taskDescription:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sit amet suscipit nisl. Maecenas lorem neque, feugiat quis est tincidunt, ultrices aliquet risus. Aliquam vitae mollis lacus, quis iaculis felis. Ut ac mauris varius, scelerisque justo ac, sodales ligula. Fusce vestibulum massa in dictum bibendum. Sed imperdiet commodo dui, quis bibendum ipsum mattis ac. Vivamus a congue velit. Pellentesque sed pulvinar dolor.",
    taskersNeeded: 2,
    requirements: ["2 taskers", "Muscles", "A toothbrush", "Philosophy degree"],
  },
  {
    icon: <Shoe size={16} />,
    color: "grape",
    label: "Cleaning shoes ",
    category: "Cleaning",
    jobTime: "Thur 12 March",
    location: "Amsterdam",
    offer: 15,
    status: "open",
    comments: 3,
    applicants: 5,
    jid: "23456gfadewggrehsgfa78",
    owner: {
      name: "Elko Lemiso",
      profileImage: "",
      uuid: "123456789",
    },
    timePosted: "6 hours",
    taskDescription:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sit amet suscipit nisl. Maecenas lorem neque, feugiat quis est tincidunt, ultrices aliquet risus. Aliquam vitae mollis lacus, quis iaculis felis. Ut ac mauris varius, scelerisque justo ac, sodales ligula. Fusce vestibulum massa in dictum bibendum. Sed imperdiet commodo dui, quis bibendum ipsum mattis ac. Vivamus a congue velit. Pellentesque sed pulvinar dolor.",
    taskersNeeded: 2,
    requirements: ["2 taskers", "Muscles", "A toothbrush", "Philosophy degree"],
  },
  {
    icon: <Shoe size={16} />,
    color: "grape",
    label: "Cleaning shoes ",
    category: "Cleaning",
    jobTime: "Thur 12 March",
    location: "Amsterdam",
    offer: 15,
    status: "open",
    comments: 3,
    applicants: 5,
    jid: "23456gfjztrjzrtjadsgfa78",
    owner: {
      name: "Elko Lemiso",
      profileImage: "",
      uuid: "123456789",
    },
    timePosted: "6 hours",
    taskDescription:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sit amet suscipit nisl. Maecenas lorem neque, feugiat quis est tincidunt, ultrices aliquet risus. Aliquam vitae mollis lacus, quis iaculis felis. Ut ac mauris varius, scelerisque justo ac, sodales ligula. Fusce vestibulum massa in dictum bibendum. Sed imperdiet commodo dui, quis bibendum ipsum mattis ac. Vivamus a congue velit. Pellentesque sed pulvinar dolor.",
    taskersNeeded: 2,
    requirements: ["2 taskers", "Muscles", "A toothbrush", "Philosophy degree"],
  },
  {
    icon: <Shoe size={16} />,
    color: "grape",
    label: "Cleaning shoes ",
    category: "Cleaning",
    jobTime: "Thur 12 March",
    location: "Amsterdam",
    offer: 15,
    status: "open",
    comments: 3,
    applicants: 5,
    owner: {
      name: "Elko Lemiso",
      profileImage: "",
      uuid: "123456789",
    },
    timePosted: "6 hours",
    jid: "23jdzfjhtfjetj456gfadsgfa78",
    taskDescription:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sit amet suscipit nisl. Maecenas lorem neque, feugiat quis est tincidunt, ultrices aliquet risus. Aliquam vitae mollis lacus, quis iaculis felis. Ut ac mauris varius, scelerisque justo ac, sodales ligula. Fusce vestibulum massa in dictum bibendum. Sed imperdiet commodo dui, quis bibendum ipsum mattis ac. Vivamus a congue velit. Pellentesque sed pulvinar dolor.",
    taskersNeeded: 2,
    requirements: ["2 taskers", "Muscles", "A toothbrush", "Philosophy degree"],
  },
  {
    icon: <Shoe size={16} />,
    color: "grape",
    label: "Cleaning shoes ",
    category: "Cleaning",
    jobTime: "Thur 12 March",
    location: "Amsterdam",
    offer: 15,
    status: "open",
    comments: 3,
    applicants: 5,
    jid: "23456gfadshzdfhfdzhzdfhfdzhgfa78",
    owner: {
      name: "Elko Lemiso",
      profileImage: "",
      uuid: "123456789",
    },
    timePosted: "6 hours",
    taskDescription:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sit amet suscipit nisl. Maecenas lorem neque, feugiat quis est tincidunt, ultrices aliquet risus. Aliquam vitae mollis lacus, quis iaculis felis. Ut ac mauris varius, scelerisque justo ac, sodales ligula. Fusce vestibulum massa in dictum bibendum. Sed imperdiet commodo dui, quis bibendum ipsum mattis ac. Vivamus a congue velit. Pellentesque sed pulvinar dolor.",
    taskersNeeded: 2,
    requirements: ["2 taskers", "Muscles", "A toothbrush", "Philosophy degree"],
  },
  {
    icon: <Shoe size={16} />,
    color: "grape",
    label: "Cleaning shoes ",
    category: "Cleaning",
    jobTime: "Thur 12 March",
    location: "Amsterdam",
    offer: 15,
    status: "open",
    comments: 3,
    applicants: 5,
    jid: "23456ghfdzjmgjndzfadsgfa78",
    owner: {
      name: "Elko Lemiso",
      profileImage: "",
      uuid: "123456789",
    },
    timePosted: "6 hours",
    taskDescription:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sit amet suscipit nisl. Maecenas lorem neque, feugiat quis est tincidunt, ultrices aliquet risus. Aliquam vitae mollis lacus, quis iaculis felis. Ut ac mauris varius, scelerisque justo ac, sodales ligula. Fusce vestibulum massa in dictum bibendum. Sed imperdiet commodo dui, quis bibendum ipsum mattis ac. Vivamus a congue velit. Pellentesque sed pulvinar dolor.",
    taskersNeeded: 2,
    requirements: ["2 taskers", "Muscles", "A toothbrush", "Philosophy degree"],
  },
  {
    icon: <Shoe size={16} />,
    color: "grape",
    label: "Cleaning shoes ",
    category: "Cleaning",
    jobTime: "Thur 12 March",
    location: "Amsterdam",
    offer: 15,
    status: "open",
    comments: 3,
    applicants: 5,
    jid: "23456gfahdzfhfdzhzrtdsgfa78",
    owner: {
      name: "Elko Lemiso",
      profileImage: "",
      uuid: "123456789",
    },
    timePosted: "6 hours",
    taskDescription:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sit amet suscipit nisl. Maecenas lorem neque, feugiat quis est tincidunt, ultrices aliquet risus. Aliquam vitae mollis lacus, quis iaculis felis. Ut ac mauris varius, scelerisque justo ac, sodales ligula. Fusce vestibulum massa in dictum bibendum. Sed imperdiet commodo dui, quis bibendum ipsum mattis ac. Vivamus a congue velit. Pellentesque sed pulvinar dolor.",
    taskersNeeded: 2,
    requirements: ["2 taskers", "Muscles", "A toothbrush", "Philosophy degree"],
  },
  {
    icon: <Shoe size={16} />,
    color: "grape",
    label: "Cleaning shoes ",
    category: "Cleaning",
    jobTime: "Thur 12 March",
    location: "Amsterdam",
    offer: 15,
    status: "open",
    comments: 3,
    applicants: 5,
    jid: "23456gfaddgfhdzfhfsgfa78",
    owner: {
      name: "Elko Lemiso",
      profileImage: "",
      uuid: "123456789",
    },
    timePosted: "6 hours",
    taskDescription:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sit amet suscipit nisl. Maecenas lorem neque, feugiat quis est tincidunt, ultrices aliquet risus. Aliquam vitae mollis lacus, quis iaculis felis. Ut ac mauris varius, scelerisque justo ac, sodales ligula. Fusce vestibulum massa in dictum bibendum. Sed imperdiet commodo dui, quis bibendum ipsum mattis ac. Vivamus a congue velit. Pellentesque sed pulvinar dolor.",
    taskersNeeded: 2,
    requirements: ["2 taskers", "Muscles", "A toothbrush", "Philosophy degree"],
  },
  {
    icon: <Shoe size={16} />,
    color: "grape",
    label: "Cleaning shoes ",
    category: "Cleaning",
    jobTime: "Thur 12 March",
    location: "Amsterdam",
    offer: 15,
    status: "open",
    comments: 3,
    applicants: 5,
    jid: "23456ggfjgfxjtrjtjfadsgfa78",
    owner: {
      name: "Elko Lemiso",
      profileImage: "",
      uuid: "123456789",
    },
    timePosted: "6 hours",
    taskDescription:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sit amet suscipit nisl. Maecenas lorem neque, feugiat quis est tincidunt, ultrices aliquet risus. Aliquam vitae mollis lacus, quis iaculis felis. Ut ac mauris varius, scelerisque justo ac, sodales ligula. Fusce vestibulum massa in dictum bibendum. Sed imperdiet commodo dui, quis bibendum ipsum mattis ac. Vivamus a congue velit. Pellentesque sed pulvinar dolor.",
    taskersNeeded: 2,
    requirements: ["2 taskers", "Muscles", "A toothbrush", "Philosophy degree"],
  },
  {
    icon: <Shoe size={16} />,
    color: "grape",
    label: "Cleaning shoes ",
    category: "Cleaning",
    jobTime: "Thur 12 March",
    location: "Amsterdam",
    offer: 15,
    status: "open",
    comments: 3,
    applicants: 5,
    jid: "23456gfjgfjfghjgfjgjfgjadsgfa78",
    owner: {
      name: "Elko Lemiso",
      profileImage: "",
      uuid: "123456789",
    },
    timePosted: "6 hours",
    taskDescription:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sit amet suscipit nisl. Maecenas lorem neque, feugiat quis est tincidunt, ultrices aliquet risus. Aliquam vitae mollis lacus, quis iaculis felis. Ut ac mauris varius, scelerisque justo ac, sodales ligula. Fusce vestibulum massa in dictum bibendum. Sed imperdiet commodo dui, quis bibendum ipsum mattis ac. Vivamus a congue velit. Pellentesque sed pulvinar dolor.",
    taskersNeeded: 2,
    requirements: ["2 taskers", "Muscles", "A toothbrush", "Philosophy degree"],
  },
  {
    icon: <Shoe size={16} />,
    color: "grape",
    label: "Cleaning shoes ",
    category: "Cleaning",
    jobTime: "Thur 12 March",
    location: "Amsterdam",
    offer: 15,
    status: "open",
    comments: 3,
    applicants: 5,
    owner: {
      name: "Elko Lemiso",
      profileImage: "",
      uuid: "123456789",
    },
    timePosted: "6 hours",
    jid: "23456gbsdbhgffadsgfa78",
    taskDescription:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sit amet suscipit nisl. Maecenas lorem neque, feugiat quis est tincidunt, ultrices aliquet risus. Aliquam vitae mollis lacus, quis iaculis felis. Ut ac mauris varius, scelerisque justo ac, sodales ligula. Fusce vestibulum massa in dictum bibendum. Sed imperdiet commodo dui, quis bibendum ipsum mattis ac. Vivamus a congue velit. Pellentesque sed pulvinar dolor.",
    taskersNeeded: 2,
    requirements: ["2 taskers", "Muscles", "A toothbrush", "Philosophy degree"],
  },
];
